services:
  - type: web
    name: taskmaster-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: your-super-secret-jwt-key
    healthCheckPath: /api/health
